name: Run AI Translator Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *' # Будет «пинговать» бота каждые 30 минут, чтобы не спал

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pyTelegramBotAPI requests

      - name: Run Bot
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        run: python translator_bot.py
