name: Run AI Translator Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pyTelegramBotAPI requests

      - name: Run Bot
        env:
          # Передаем секреты из настроек GitHub в код бота
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        run: python translator_bot.py
